# Generated by Django 4.2.26 on 2025-12-20 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads_post', '0007_vehicle_plate_number_unique_and_verification_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleverificationresult',
            name='document_fuel_type',
            field=models.CharField(blank=True, help_text='Fuel type extracted from document', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicleverificationresult',
            name='document_manufacturer',
            field=models.CharField(blank=True, help_text='Manufacturer from document', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='vehicleverificationresult',
            name='document_match_score',
            field=models.FloatField(blank=True, help_text='Overall match score between form data and document (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='vehicleverificationresult',
            name='document_model_year',
            field=models.CharField(blank=True, help_text='Model year from document', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicleverificationresult',
            name='document_plate_number',
            field=models.CharField(blank=True, help_text='Plate number from document', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicleverificationresult',
            name='document_vehicle_class',
            field=models.CharField(blank=True, help_text='Vehicle class from document', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('emission_test', 'Emission Test Certificate'), ('ownership_book', 'Ownership Book')], max_length=20)),
                ('document_file', models.FileField(upload_to='vehicle_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_data', models.JSONField(blank=True, help_text='Vehicle details extracted from document by AI', null=True)),
                ('extraction_confidence', models.FloatField(blank=True, help_text='Confidence score for extraction (0-100)', null=True)),
                ('extraction_completed_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ads_post.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Document',
                'verbose_name_plural': 'Vehicle Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
